### ISSUE TITLE
unsupported format 'pyimport'

### ISSUE THREAD

**Issue by jerem0808** [CiscoTestAutomation/ncdiff#10]
Hi
I have a built a Jenkins pipeline which calls a python script which in turn tries to get the netconf schema. 
Important notice is that i'm using a jump host. 
But i don't think this is causing any issues because i'm able to retrieve the configuration with 
`pcr1.get_config(source="running").data_xml`
I have this simple script
```
    jumpbox_public_addr = "x.x.x.x"
    jumpbox_private_addr = jumpbox_public_addr
    target_addr_1 = input_args[1]
    target_addr_2 = input_args[4]

    jumpbox = paramiko.SSHClient()
    k = paramiko.RSAKey.from_private_key_file(os.environ["SSH_Keys"])
    jumpbox.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    jumpbox.connect(
        jumpbox_public_addr,
        username=os.environ["jump_user"],
        allow_agent=False,
        pkey=k,
    )
    # First connection
    jumpbox_transport = jumpbox.get_transport()
    src_addr = (jumpbox_private_addr, 22)
    dest_addr = (target_addr_1, 830)
    jumpbox_channel = jumpbox_transport.open_channel(
        "direct-tcpip", dest_addr, src_addr
    )
    # ncdiff.manager.ModelDevice
    pcr1 = manager.connect(
        host=target_addr_1,
        username=input_args[2],
        password=input_args[3],
        hostkey_verify=False,
        sock=jumpbox_channel,
    )
pcr1.scan_models(download="force")
```

But scan_models returns an error: 

> error /home/jenkins/workspace/PCR_Pipes/PCR_Diff/PCR/yang/*.yang: [Errno 2] No such file or directory: '/home/jenkins/workspace/PCR_Pipes/PCR_Diff/PCR/yang/*.yang'
Traceback (most recent call last):
  File "pcr_compare.py", line 131, in <module>
    main(sys.argv)
  File "pcr_compare.py", line 82, in main
    pcr1.scan_models(download="force")
  File "/usr/local/lib/python3.8/site-packages/ncdiff/manager.py", line 266, in scan_models
    self.compiler = ModelCompiler(folder)
  File "/usr/local/lib/python3.8/site-packages/ncdiff/model.py", line 628, in __init__
    self.build_dependencies()
  File "/usr/local/lib/python3.8/site-packages/ncdiff/model.py", line 676, in build_dependencies
    self.dependencies = etree.XML(stdout.decode(), parser)
  File "src/lxml/etree.pyx", line 3216, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
pcr_compare.py
Building dependencies: pyang --plugindir /plugins -p ./yang/ -f pyimport ./yang/*.yang
pyang return code is 1
unsupported format 'pyimport'

It seems that the directory (self.pyang_plugins = os.path.dirname(\_\_file__) + '/plugins') is not correct. I don't understand why. 
I'm using a docker container with
I'm using python 3.8.7 and ncdiff 20.10

Thank you for your help

**Comment by jerem0808** [comment]
I think that the error was in fact that models_loadable is empty
