### ISSUE TITLE
NameError - undefined variable

### ISSUE THREAD

**Issue by cukiernick** [CiscoTestAutomation/ncdiff#18]
Current master (bd1566f73e989454780c39ab6479baffaaaf9c58) throws `NameError` because of undefined 'repository' variable

```
Traceback (most recent call last):
  File "script1.py", line 14, in <module>
    m.scan_models()
  File "/home/user/ws/ncdiff/src/ncdiff/manager.py", line 273, in scan_models
    d = ModelDownloader(self, folder)
  File "/home/user/ws/ncdiff/src/ncdiff/model.py", line 738, in __init__
    repo = repository.FileRepository(path=self.dir_yang)
NameError: name 'repository' is not defined
```

```
$ flake8 src --select=F821
src/ncdiff/config.py:116:32: F821 undefined name 'Request'
src/ncdiff/config.py:118:27: F821 undefined name 'RestconfCalculator'
src/ncdiff/config.py:119:32: F821 undefined name 'SetRequest'
src/ncdiff/config.py:121:27: F821 undefined name 'gNMICalculator'
src/ncdiff/model.py:738:16: F821 undefined name 'repository'
```

**Comment by ademz** [comment]
Hell @cukiernick ,

Thank you for your report. I created a pr for this case.

Adem Oztas
